version: '3'
services:
        react-app:
                build: src/client
                environment:
                        - PORT=3000
                        - NODE_ENV=dev
                        - ENV_NAME=local
                ports:
                        - "3000:3000"
                volumes:
                        - ./src/client:/opt/app/src
                        - ./src/client/public/index.html:/opt/app/public/index.html

        server:
                build: src/server
                ports:
                        - "8080:8080"
                volumes:
                        - ./src/server:/opt/app/src
