version: '3'
services:
        react-app:
                build: ./client
                environment:
                        - PORT=3000
                        - NODE_ENV=dev
                        - ENV_NAME=local
                ports:
                        - "3000:3000"
                volumes:
                        - ./client:/opt/app/src
                        - ./public/index.html:/opt/app/public/index.html

        server:
                build: ./server
                ports:
                        - "8080:8080"
