version: '3'
services:
  app:
    build: ./client
    environment:
    - PORT=3000
    - NODE_ENV=dev
    - ENV_NAME=local
    ports:
    - "3000:3000"
    volumes:
    - ./client:/opt/app/src
    - ./public:/opt/app/public